### PR TITLE
support for gnome-shell40/gtk4

### LINKED ISSUE #37: Add support for Gnome 40
Title says it all

### PR DESCRIPTION
**Pull request by msschw**
Tried to resolve #37. Preserving gtk3 path using shell-version conditionals.

### CODE REVIEW

**Comment by gicmo** [comment]
Omg this is awesome!

**Comment by cleveHEX** [comment]
@gicmo do you have any plans on merging this?

**Comment by gicmo** [comment]
I am so sorry, I have been busy with other work and did not yet get to test it.

**Comment by mz1193** [comment]
> I am so sorry, I have been busy with other work and did not yet get to test it.

For what it's worth, I compiled this commit locally on my machine and have been using it for weeks with no issue. Seems like it's probably good to go, but more people testing it is probably a good idea. :+1:

**Comment by gicmo** [comment]
All commits hit the main branch! Thanks so much everyone!

**Pull request closed without merging**
