### PR TITLE
Add support for shell versions 44 and 45

### LINKED ISSUE #62: Publish GNOME 43 version to extensions.gnome.org
https://extensions.gnome.org/extension/1852/gamemode/ only supports GNOME 42 at the moment. Can you please publish version 8 for GNOME 43 compatibility on that website? Thanks @gicmo .

### PR DESCRIPTION
**Pull request by cleveHEX**
Fixes #62 with a release afterwards.

### CODE REVIEW

**Comment by BloodyIron** [comment]
Looking for Gnome 44 support to hit main extension repo. Any anticipated timeline on that? :)

**Comment by cleveHEX** [comment]
You have to ask @gicmo , I don't remember why I added 45, that version does not exist, it was probably a mistake, will remove soon.

**Comment by lukurde** [comment]
Hello all. Gnome 44 has been out for almost 2 months now and the plugin still doesn't support it. The last version listed on extensions.gnome.org shows Gnome 42 which is 2 releases behind. The plugin shipped with Fedora 38 doesn't support Gnome 44 shipped with said OS... Can we bump the version or is there a blocker behind it?

**Comment by lukurde** [comment]
Hey @benzea, I don't know if that was the intent but you've also merged support for the future version of Gnome 45 which is scheduled to be released in September.

**Comment by yochananmarqos** [comment]
@cewbdex Please remove the false GNOME 45 compatibility. See #70

**Comment by cleveHEX** [comment]
I can't do anything further, it was merged before I could implement a fix, I just opened PR, so can you do.

**Comment by yochananmarqos** [comment]
@cewbdex Oops, I meant to tag @benzea.

**Comment by fjsevilla-dev** [comment]
@yochananmarqos I have just fixed the mistake. Now I'm going to see if it's too much work to support the extension to gnome-shell 45...

**Pull request merged**
